spring.application.name=Blog_website

spring.datasource.url=jdbc:mysql://database-1.cd6iswegk7zq.ap-south-1.rds.amazonaws.com:3306/blogdb
spring.datasource.username = admin
spring.datasource.password = fazilars1234

spring.jpa.hibernate.ddl-auto = update 
spring.jpa.show-sql = true
jwt.secret = "ALLAHTERASATHHYTUKYUDARNAMERAYAARHAPPYHONARAHAFAZILTUJARACHASARAHTHOACHA"
