spring.application.name=Blog_website

spring.datasource.url = jdbc:mysql://localhost:3306/blog_website
spring.datasource.username = root
spring.datasource.password = fazilars123

spring.jpa.hibernate.ddl-auto = update 
spring.jpa.show-sql = true
jwt.secret = "ALLAHTERASATHHYTUKYUDARNAMERAYAARHAPPYHONARAHAFAZILTUJARACHASARAHTHOACHA"